#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASS';
  CREATE DATABASE $APP_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_DB_USER;
  \connect $APP_DB_NAME $APP_DB_USER
  BEGIN;
  CREATE TABLE IF NOT EXISTS todos (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    title text NOT NULL,
    is_complete boolean NOT NULL,
    CONSTRAINT pk_todos PRIMARY KEY (id)
  );
  INSERT INTO todos(title, is_complete) VALUES ('todo 1', true);

  INSERT INTO todos(title, is_complete) VALUES ('todo 2', false);

  INSERT INTO todos(title, is_complete) VALUES ('todo 3', false);

  SELECT * FROM todos;
  
  COMMIT;
EOSQL
